version: '3.3'

services:
  db:
    image: mysql:8.0.33
    volumes:
      - axum_db_data:/var/lib/mysql
    restart: always
    env_file: .env
    ports:
      - 3306:3306
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  axum_db_data: {}
